WebLayer/Pages/Users/Admin.cshtml.cs
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceLayer.I_R;
using WebLayer.Pages.Shared.Helpers.Files;

namespace WebLayer.Pages.Users;
public class AdminModel : PageModel
{
    private readonly IProduct _productService;
    private readonly IFileHelper _fileHelper;

    public AdminModel(IProduct pService, IFileHelper fileHelper )
    {
        _productService = pService;
        _fileHelper = fileHelper;
    }
    [BindProperty(SupportsGet = true)]
    public string? SearchString { get; set; }
    [BindProperty]
    public int ProductId { get; set; }
    [BindProperty]
    public Product Product { get; set; }
    [BindProperty]
    public IFormFile UploadImage { get; set; }
    public IQueryable<Product> Products { get; set; }
    public List<SelectListItem>? Catagories { get; set; }
    public List<SelectListItem>? Brands { get; set; }
    public List<SelectListItem>? Sets { get; set; }
    [BindProperty(SupportsGet = true)]
    public int SelectCat { get; set; }
    [BindProperty(SupportsGet = true)]
    public string SelectSet { get; set; }

    public async Task OnGet()
    {
        List<Category> catagoriesTypeModels = await _productService.GetAllCategories();
        List<Brand> brandTypeModels = await _productService.GetAllBrandsAsync();
        //List<Set> setTypeModels = await _productService.GetAllSetsAsync();
        Catagories = catagoriesTypeModels.Select(ctm => new SelectListItem
        {
            Value = ctm.CategoryId.ToString(),
            Text = ctm.Name.ToString()
        }).ToList();
        Brands = brandTypeModels.Select(b => new SelectListItem
        {
            Value = b.BrandId.ToString(),
            Text = b.Name.ToString()
        }).ToList();
        //Sets = setTypeModels.Select(s => new SelectListItem
        //{
        //    Value = s.SetId.ToString(),
        //    Text = s.SetName.ToString()
        //}).ToList();
        if (!string.IsNullOrEmpty(SearchString))
        {
            Products = _productService.FindAllPage(_productService.FindAll().Where(s => s.Name.Contains(SearchString)).Include(p => p.Image).Include(p => p.Brand).Include(p => p.Category), 1, 9);
        }
        if (SelectCat > 0)
        {
            Products = _productService.FindAllPage(_productService.FindAll().Where(s => s.Fk_CategoryId == SelectCat).Include(p => p.Image).Include(p => p.Brand).Include(p => p.Category), 1, 9);
        }
        if (!string.IsNullOrEmpty(SelectSet))
        {
            Products = _productService.FindAllPage(_productService.FindAll().Where(s => s.Fk_SetId == SelectSet).Include(p => p.Image).Include(p => p.Brand).Include(p => p.Category), 1, 9);
        }
        if(string.IsNullOrEmpty(SelectSet) && SelectCat < 1 && string.IsNullOrEmpty(SearchString))
        {
            Products = _productService.FindAllPage(_productService.FindAll().Include(p => p.Image).Include(p => p.Brand).Include(p => p.Category), 1, 9);
        }
    }
    public async Task OnPostCreate()
    {
        string checkImage = UploadImage.FileName.Split('.').Last().ToUpper();
        if (checkImage == "JPG" | checkImage == "JPEG" | checkImage == "PNG")
        {
            await _fileHelper.UploadFileAsync(UploadImage);
            Product.Image = new ();
            Product.Image.Path = $"\\Image\\Card\\{UploadImage.FileName}";
            await _productService.AddItemAsync(Product);
            await _productService.CommitAsync();
            await OnGet();
        }
    }
    public async Task<IActionResult> OnPostDelete()
    {
        Product foundProduct = await _productService.FindByIdAsync(ProductId);
        _productService.Delete(foundProduct);
        await _productService.CommitAsync();
        return RedirectToPage("Users/Admin");
    }
}

WebLayer/Pages/Users/Login.cshtml.cs
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServiceLayer.I_R;

namespace WebLayer.Pages.Users
{
    public class LoginModel : PageModel
    {
        private readonly IUser _userService;
        public LoginModel(IUser userService)
            => _userService = userService;

        [BindProperty]
        public User User { get; set; }
        [BindProperty]
        public string? PasswordCompared { get; set; }
        public void OnGet()
        {

        }
        public IActionResult OnPostLogin()
        {
            User FoundUser = _userService.Login(User.Email, User.Password);
            if (FoundUser != null)
            {
                HttpContext.Session.SetString("userId", FoundUser.UserId.ToString());
                if (FoundUser.Admin)
                {
                    HttpContext.Session.SetString("userAdmin", FoundUser.Admin.ToString());
                    return RedirectToPage("/Users/Admin");
                }
                return RedirectToPage("/Users/UserSite");
            }
            return Page();
        }
        public IActionResult OnPostCreate()
        {
            if (User.Password == PasswordCompared)
            {
                _userService.AddItemAsync(User);
                _userService.CommitAsync();
            }
            return Page();
        }
    }
}

WebLayer/Pages/Users/UserSite.cshtml.cs
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServiceLayer.I_R;

namespace WebLayer.Pages.Users;

public class UserSiteModel : PageModel
{
    private readonly IUser _userService;
    public UserSiteModel(IUser userService)
    {
        _userService = userService;
    }
    public User User { get; set; }
    public async Task OnGet()
    {
        if (!string.IsNullOrEmpty( HttpContext.Session.GetString("userId")))
            User = await _userService.GetUserByGuidAsync(Guid.Parse(HttpContext.Session.GetString("userId")));
    }
}

WebLayer/Pages/Users/Admin.cshtml
@page
@model WebLayer.Pages.Users.AdminModel
@{

}
<div class="container">
    <br />
    <div class="row">
        <form>
            <p>
                <div class="col l2">

            <select asp-for="SelectCat" asp-items="Model.Catagories">
                <option value="">Kategori</option>
            </select>
                    <select asp-for="SelectSet" asp-items="Model.Sets">
                        <option value="">Set</option>
                    </select>
                </div>
                <div class="input-field col l6">
                    <input id="icon_title" type="text" class="validate" asp-for="SearchString">
                    <label for="icon_title">Søg på titel</label>
                    <input class="waves-effect waves-light btn view right" type="submit" value="Filter" />
                </div>
            </p>
        </form>
        <a class="waves-effect waves-light btn view col l2 right" onclick="$('#modal1').modal('open');">Opret Product</a>
    </div>
    <br />
    <table class="striped highlight">
        <thead>
            <tr>
                <th>Titel</th>
                <th>Beskrivelse</th>
                <th>Pris</th>
                <th>Brand</th>
                <th>Kategori</th>
                <th>Set</th>
                <th>Rediger</th>
                <th>Slet</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Products)
            {
                <form method="post">
                    <input hidden value="@item.ProductId" asp-for="ProductId">
                <tr>
                    <th>@item.Name</th>
                    <th>@item.Description</th>
                    <th>@item.Price</th>
                    <th>@item.Brand.Name</th>
                    <th>@item.Category.Name</th>
                    <th>@item.Fk_SetId</th>
                    <th>
                        <a class="btn waves-effect waves-light yellow darken-1" asp-page="/Products/UpdateProduct" asp-route-ProductId="@item.ProductId">
                            <i class="material-icons">edit</i>
                        </a>
                    </th>
                    <th>
                        <button class="btn waves-effect waves-light red darken-1" type="submit" name="action" asp-page-handler="Delete">
                            <i class="material-icons">delete</i>
                        </button>
                    </th>
                </tr>
                </form>
            }
        </tbody>
    </table>



    <div id="modal1" class="modal">
        <div class="modal-content">
            <div class="row">
                <h4 class="col">Opret product</h4>
                <a href="#!" class="modal-close waves-effect waves-green btn-flat right col">Luk</a>
            </div>
            <form class="col s12" method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">title</i>
                        <input id="icon_prefix" type="text" class="validate" asp-for="Product.Name">
                        <label for="icon_prefix">Title</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">description</i>
                        <input id="icon_lastname" type="text" class="validate" asp-for="Product.Description">
                        <label for="icon_lastname">Beskrivelse</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">attach_money</i>
                        <input id="icon_add" type="number" class="validate" asp-for="Product.Price">
                        <label for="icon_add">Pris</label>
                    </div>
                    <div class="input-field col s6">
                        <select asp-for="Product.Fk_SetId" asp-items="@Model.Sets" required>
                            <option value="">Valg</option>
                        </select>
                        <label>Set</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <select asp-for="Product.Fk_BrandId" asp-items="@Model.Brands" required>
                            <option value="">Valg</option>
                        </select>
                        <label>Brand</label>
                    </div>
                    <div class="input-field col s6">
                        <select asp-for="Product.Fk_CategoryId" asp-items="@Model.Catagories" required>
                            <option value="">Valg</option>
                        </select>
                        <label>Kategori</label>
                    </div>
                </div>
                <div class="row">

                    <div class="file-field input-field">
                        <div class="btn">
                            <span>File</span>
                            <input type="file" asp-for="UploadImage">
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                        </div>
                    </div>
                </div>
                <button class="btn waves-effect waves-light" type="submit" name="action" asp-page-handler="Create">
                    Opret
                    <i class="material-icons right">send</i>
                </button>
            </form>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#modal1').modal();
    });
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>

WebLayer/Pages/Users/Login.cshtml
@page
@model WebLayer.Pages.Users.LoginModel
@{
    ViewData["Title"] = "Login";
}
<div class="container">
    <form class="col s12 mb" method="post">
        <h2>Login</h2>
        <div class="row">
            <div class="input-field col s12">
                <input id="email" type="email" class="validate" asp-for="User.Email">
                <label for="email">Email</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input id="password" type="password" class="validate" asp-for="User.Password">
                <label for="password">Password</label>
            </div>
        </div>
        <button class="btn waves-effect waves-light" asp-page-handler="Login">Login</button>
        <a class="waves-effect waves-light btn view" onclick="$('#modal1').modal('open');">Opret</a>
    </form>
    <div id="modal1" class="modal">
        <div class="modal-content">
            <div class="row">
                <h4 class="col">Opret bruger</h4>
                <a href="#!" class="modal-close waves-effect waves-green btn-flat right col">Luk</a>
            </div>
            <form class="col s12" method="post">
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">account_circle</i>
                        <input id="icon_prefix" type="text" class="validate" asp-for="User.FirstName">
                        <label for="icon_prefix">Fornavn</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix"></i>
                        <input id="icon_lastname" type="tel" class="validate" asp-for="User.Lastname">
                        <label for="icon_lastname">Efternavn</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">home</i>
                        <input id="icon_add" type="text" class="validate" asp-for="User.Address">
                        <label for="icon_add">Addresse</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix"></i>
                        <input id="icon_zip" type="tel" class="validate" asp-for="User.Fk_ZipCodeId">
                        <label for="icon_zip">Postnummer</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">email</i>
                        <input id="icon_email" type="email" class="validate" asp-for="User.Email">
                        <label for="icon_email">Email</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">lock</i>
                        <input id="icon_pass1" type="password" class="validate" asp-for="User.Password">
                        <label for="icon_pass1">Password</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix"></i>
                        <input id="icon_pass2" type="password" class="validate" asp-for="PasswordCompared">
                        <label for="icon_pass2">Gentag password</label>
                    </div>
                </div>
                <button class="btn waves-effect waves-light" type="submit" name="action" asp-page-handler="Create">
                    Opret
                    <i class="material-icons right">send</i>
                </button>
            </form>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#modal1').modal();
    });
</script>

WebLayer/Pages/Users/UserSite.cshtml
@page
@model WebLayer.Pages.Users.UserSiteModel
@{
}
<div class="container">
    <div>@Model.User.FirstName</div>
    <table>
        <thead>
            <tr>
                <th>Ordre</th>
                <th>Oprettet</th>
           
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.User.Ordres)
            {
                <tr>
                    <td>@item.OrdreId</td>
                    <td>@item.Created</td>
                 
                </tr>
                
            }
          
        </tbody>
    </table>
</div>