WebLayer/Pages/Index.cshtml.cs
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ServiceLayer.DTO;
using ServiceLayer.I_R;
using WebLayer.SessionHelper;

namespace WebLayer.Pages
{
    public class IndexModel : PageModel
    {
        public const string SessionKey = "Cart";
        private readonly ILogger<IndexModel> _logger;
        private readonly IProduct _productService;

        public IndexModel(ILogger<IndexModel> logger, IProduct productService)
        {
            _logger = logger;
            _productService = productService;
        }

        public IQueryable<Product> Products { get; set; }
        [BindProperty]
        public Product Product { get; set; }
        public void OnGet()
        {
            Products = _productService.FindAll().Include(p => p.Image).Include(p => p.Set).OrderByDescending(p => p.Set.SetRealse).Take(3);
        }
        public void OnPostAddToCart()
        {
            //BrandId = amount
            if (HttpContext.Session.Get<List<SessionDataCart>>(SessionKey) == null)
            {
                List<SessionDataCart> nyCartSession = new List<SessionDataCart> { new SessionDataCart { ProductId = Product.ProductId, Amount = Product.Fk_BrandId } };
                HttpContext.Session.Set(SessionKey, nyCartSession);
                HttpContext.Session.Set<int>("CartAmount", Product.Fk_BrandId);
                HttpContext.Session.SetString("CartAmountString", Product.Fk_BrandId.ToString());
            }
            else
            {
                List<SessionDataCart> cartSession = HttpContext.Session.Get<List<SessionDataCart>>(SessionKey);
                int amount = HttpContext.Session.Get<int>("CartAmount");
                if (cartSession.Any(a => a.ProductId == Product.ProductId))
                {
                    SessionDataCart foundProduct = cartSession.Where(a => a.ProductId == Product.ProductId).FirstOrDefault();
                    foundProduct.Amount++;

                }
                else
                {
                    cartSession.Add(
                    new SessionDataCart { ProductId = Product.ProductId, Amount = Product.Fk_BrandId });

                }
                HttpContext.Session.Set(SessionKey, cartSession);
                HttpContext.Session.Set<int>("CartAmount", amount + Product.Fk_BrandId);
                HttpContext.Session.SetString("CartAmountString", (amount + Product.Fk_BrandId).ToString());
            }
            OnGet();
        }
    }
}

WebLayer/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebLayer</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebLayer.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
</head>
@{
    string amount = Context.Session.GetString("CartAmountString");
}
<body>
    <header>
        <nav class="cyan darken-3" role="navigation">
            <div class="nav-wrapper container ">
                <a id="logo-container" asp-page="/Index" class="brand-logo left white-text">Krillz Cardz</a>
                @if (string.IsNullOrEmpty(Context.Session.GetString("userId")))
                {
                    <ul class="right">
                        <a class="white-text" asp-page="/Users/Login">Login</a>
                    </ul>
                }
                else
                {
                    if (string.IsNullOrEmpty(Context.Session.GetString("userAdmin")))
                    {
                        <ul class="right">
                            <a class="white-text" asp-page="/Users/UserSite">Profil</a>
                        </ul>
                    }
                    else
                    {
                        <ul class="right">
                            <a class="white-text" asp-page="/Users/Admin">Profil</a>
                        </ul>
                    }
                }
                <ul class="right">
                    <a class="waves-effect btn black white-text" asp-page="/Products/Cart"><i class="material-icons left">shopping_cart</i>Indkøbskurv 
                        @if (!string.IsNullOrEmpty(Context.Session.GetString("CartAmountString"))) 
                        {
                            <div>
                            (@amount)
                            </div>
                        }
                    </a>
                </ul>
            </div>
        </nav>
    </header>

    <main role="main">
        @RenderBody()
    </main>

    <footer class="page-footer cyan darken-3">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Kontakt</h5>
                    <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>
                </div>
                <div class="col l3 s12">
                    <h5 class="white-text">Settings</h5>
                    <ul>
                        <li><a class="white-text" href="#!">Link 1</a></li>
                        <li><a class="white-text" href="#!">Link 2</a></li>
                        <li><a class="white-text" href="#!">Link 3</a></li>
                        <li><a class="white-text" href="#!">Link 4</a></li>
                    </ul>
                </div>
                <div class="col l3 s12">
                    <h5 class="white-text">Connect</h5>
                    <ul>
                        <li><a class="white-text" href="#!">Link 1</a></li>
                        <li><a class="white-text" href="#!">Link 2</a></li>
                        <li><a class="white-text" href="#!">Link 3</a></li>
                        <li><a class="white-text" href="#!">Link 4</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
            </div>
        </div>
    </footer>
    @*<partial name="_ValidationScriptsPartial"></partial>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="~/js/materialize.js"></script>
    <script src="~/js/init.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebLayer/Pages/Shared/_ProductPartial.cshtml
@model Product
@{
}
<div class="card hoverable sticky-action col s12 l3">
    <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="@Model.Image.Path" style="height: 250px;">
    </div>
    <div class="card-content">
        <span class=" activator grey-text text-darken-4">@Model.Name</span>
        <p class="red-text">@Model.Price Kr.</p>
    </div>
    <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">@Model.Name<i class="material-icons right">close</i></span>
        <p>@Model.Description</p>
        <p>Set: @Model.Fk_SetId</p>
        <p>@Model.Fk_CategoryId</p>
    </div>
    <form method="post">
        <input hidden asp-for="@Model.ProductId" value="@Model.ProductId"/>
        <div class="input-field">
            <input asp-for="@Model.Fk_BrandId" id="first_name" type="text" class="validate">
            <label for="first_name">Antal</label>
        </div>
        <div class="card-action">
            <button class="waves-effect btn black white-text" asp-page-handler="AddToCart">I kurv</button>
        </div>
    </form>
</div>
<div class="col s1"></div>