WebLayer/Pages/Products/AllProducts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServiceLayer.I_R;
using DataLayer.Entities;
using Microsoft.EntityFrameworkCore;
using WebLayer.SessionHelper;

namespace WebLayer.Pages.Products;

public class AllProductsModel : PageModel
{
    public const string SessionKey = "Cart";
    private readonly IProduct _productService;
    public AllProductsModel(IProduct service)
    {
        _productService = service;
    }
    [BindProperty(SupportsGet = true)]
    public int CurrentPage { get; set; } = 1;

    [BindProperty(SupportsGet = true)]
    public int PageSize { get; set; } = 9;
    public IQueryable<Product> Products { get; set; }
    [BindProperty]
    public Product Product { get; set; }
    public void OnGet()
    {
        Products = _productService.FindAllPage(_productService.FindAll().Include(p => p.Image), CurrentPage, PageSize);
    }
    public void OnPostAddToCart() 
    {
        //BrandId = amount
        if (HttpContext.Session.Get<List<SessionDataCart>>(SessionKey) == null)
        {
            List<SessionDataCart> nyCartSession = new List<SessionDataCart> { new SessionDataCart { ProductId = Product.ProductId, Amount = Product.Fk_BrandId } };
            HttpContext.Session.Set(SessionKey, nyCartSession);
            HttpContext.Session.Set<int>("CartAmount", Product.Fk_BrandId);
            HttpContext.Session.SetString("CartAmountString", Product.Fk_BrandId.ToString());
        }
        else
        {
            List<SessionDataCart> cartSession = HttpContext.Session.Get<List<SessionDataCart>>(SessionKey);
            int amount = HttpContext.Session.Get<int>("CartAmount");
            if (cartSession.Any(a => a.ProductId == Product.ProductId))
            {
                SessionDataCart foundProduct = cartSession.Where(a => a.ProductId == Product.ProductId).FirstOrDefault();
                foundProduct.Amount++;    
            }
            else
            {
                cartSession.Add(
                new SessionDataCart { ProductId = Product.ProductId, Amount = Product.Fk_BrandId });   
            }
            HttpContext.Session.Set(SessionKey, cartSession);
            HttpContext.Session.Set<int>("CartAmount", amount + Product.Fk_BrandId);
            HttpContext.Session.SetString("CartAmountString", (amount + Product.Fk_BrandId).ToString());
        }
        OnGet();
    }
}

WebLayer/Pages/Products/Cart.cshtml.cs
using DataLayer.Entities;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebLayer.SessionHelper;
using ServiceLayer.I_R;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebLayer.Pages.Products
{
    public class CartModel : PageModel
    {
        private readonly IProduct _productService;
        private readonly IOrdre _ordreService;
        private readonly IUser _userService;
        public CartModel(IProduct service, IOrdre ordreService, IUser userService)
        {
            _productService = service;
            _ordreService = ordreService;
            _userService = userService;
        }
        public List<CartProducts> CartProducts { get; set; } = new();
        public decimal TotalPrice { get; set; }
        [BindProperty]
        public Product Product { get; set; }
   
        public SelectList? Payments { get; set; } =new SelectList(new List<string>(), "PaymentId", "PaymentOption");
  
        public SelectList? Deliverys { get; set; } = new SelectList(new List<string>(), "PaymentId", "PaymentOption");
        [BindProperty]
        public Ordre Ordre { get; set; }
        public User User { get; set; } = new();

        public async Task OnGet()
        {
            if (HttpContext.Session.Get<List<SessionDataCart>>("Cart") != null)
            {
                List<SessionDataCart> shoppingCart = new();
                shoppingCart = HttpContext.Session.Get<List<SessionDataCart>>("Cart");
                foreach (SessionDataCart data in shoppingCart) 
                {
                    CartProducts.Add( new CartProducts { 
                        Product = await _productService.FindByIdAsync(data.ProductId),
                        Amount = data.Amount
                    });
                }
                TotalPrice = CartProducts.Sum(p => p.Product.Price * p.Amount);
            }
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userId")))
            {
                Payments = new SelectList(_ordreService.GetAllPayments(), "PaymentId", "PaymentOption");
                Deliverys = new SelectList(_ordreService.GetDeliveries(), "DeliveryId", "DeliveryOption");
                User = await _userService.GetUserByGuidAsync(Guid.Parse(HttpContext.Session.GetString("userId")));
            }
        }
        public IActionResult OnPostDelete()
        {
            List<SessionDataCart> sessionDatas = HttpContext.Session.Get<List<SessionDataCart>>("Cart");
            int index = Exists(sessionDatas, Product.ProductId);
            sessionDatas.RemoveAt(index);
            HttpContext.Session.Set<List<SessionDataCart>>("Cart", sessionDatas);
            return RedirectToPage("/Products/Cart");
        }
        private int Exists(List<SessionDataCart> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].ProductId == id)
                {
                    return i;
                }
            }
            return -1;
        }
        public async Task<IActionResult> OnPostCreate()
        {
            List<OrdreProduct> op = new();
            List<SessionDataCart> shoppingCart = new();
            shoppingCart = HttpContext.Session.Get<List<SessionDataCart>>("Cart");
            foreach (SessionDataCart data in shoppingCart)
            {
                op.Add(new OrdreProduct
                {
                    Fk_ProductId = data.ProductId,
                    Amount = data.Amount
                });
            }
            Ordre.Products = op;
            Ordre.Fk_UserId = Guid.Parse(HttpContext.Session.GetString("userId"));
            await _ordreService.AddItemAsync(Ordre);
            await _ordreService.CommitAsync();
            return RedirectToPage("/Index");
        }
    }
}

WebLayer/Pages/Products/UpdateProduct.cshtml.cs
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using ServiceLayer.I_R;
using System.Data;
using WebLayer.Pages.Shared.Helpers.Files;

namespace WebLayer.Pages.Products;

public class UpdateProductModel : PageModel
{
    private readonly IProduct _productService;

    private readonly IFileHelper _fileHelper;

    public UpdateProductModel(IProduct service, IFileHelper fileHelper)
    {
        _productService = service;
        _fileHelper = fileHelper;
    }
    [BindProperty(SupportsGet = true)]
    public int ProductId { get; set; }
    [BindProperty]
    public Product Product  { get; set; }
    [BindProperty]
    public List<SelectListItem>? Catagories { get; set; }
    [BindProperty]
    public List<SelectListItem>? Brands { get; set; }
    //[BindProperty]
    //public List<SelectListItem>? Sets { get; set; }
    [BindProperty]
    public IFormFile? UploadImage { get; set; }
    public SelectList Sets { get; set; }
    public async Task<IActionResult> OnGetAsync()
    {
        if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userAdmin")))
        {
            Product = await _productService.GetProductByIdAsync(ProductId);
            List<Category> catagoriesTypeModels = await _productService.GetAllCategories();
            List<Brand> brandTypeModels = await _productService.GetAllBrandsAsync();
            List<SetDTO> setTypeModels = await _productService.GetAllSetsAsync();
            Catagories = catagoriesTypeModels.Select(ctm => new SelectListItem
            {
                Value = ctm.CategoryId.ToString(),
                Text = ctm.Name.ToString()
            }).ToList();
            Brands = brandTypeModels.Select(b => new SelectListItem
            {
                Value = b.BrandId.ToString(),
                Text = b.Name.ToString()
            }).ToList();
            //Sets = setTypeModels.Select(s => new SelectListItem
            //{
            //    Value = s.SetId.ToString(),
            //    Text = s.SetName.ToString()
            //}).ToList();
            Sets = new SelectList(await _productService.GetAllSetsAsync(), "SetId", "SetName");

            return Page();
        }
        return RedirectToPage("/Index");
    }
    public async Task<IActionResult> OnPostUpdate()
    {
        if (UploadImage != null)
        {
            _fileHelper.DeleteFile(Product.Image.Path);
            string checkImage = UploadImage.FileName.Split('.').Last().ToUpper();
        
            if (checkImage == "JPG" | checkImage == "JPEG" | checkImage == "PNG")
            {
                await _fileHelper.UploadFileAsync(UploadImage);
                Product.Image = new();
                Product.Image.Path = $"\\Image\\Card\\{UploadImage.FileName}";      
            }
        }
        if (Product.Price == decimal.Zero) 
        {
            
        }
        if (ModelState.IsValid)
        {
            await _productService.UpdateItemAsync(Product);
            await _productService.CommitAsync();
            return RedirectToPage("/Users/Admin");
        }
        else
        {
            //Sets = new SelectList(await _productService.GetAllSetsAsync(), "SetId", "SetName");
            //return RedirectToPagePermanent("/Products/UpdateProduct");

            return Page();
        }
    }
}

WebLayer/Pages/Products/AllProducts.cshtml
@page
@model WebLayer.Pages.Products.AllProductsModel
@{
    ViewData["Title"] = "Products";
}
<div class="container">
    <div class="row">
        <h3 class="center">Produkter</h3>
    </div>
    <div class="row">
        @foreach (var item in Model.Products)
        {
            <partial name="_ProductPartial" model="item"/>
        }
    </div>
    <div class=" row">
        <ul class="pagination center">
            <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
            <li class="active"><a href="#!">1</a></li>
            <li class="waves-effect"><a href="#!">2</a></li>
            <li class="waves-effect"><a href="#!">3</a></li>
            <li class="waves-effect"><a href="#!">4</a></li>
            <li class="waves-effect"><a href="#!">5</a></li>
            <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
        </ul>
    </div>
</div>

WebLayer/Pages/Products/Cart.cshtml
@page
@model WebLayer.Pages.Products.CartModel
@{
}
<div class="container">
    <table class="highlight">
        <thead>
            <tr>
                <th>vare</th>
                <th>Price</th>
                <th>Antal</th>
                <th>Slet</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in @Model.CartProducts)
            {
                <tr>
                    <td>@item.Product.Name</td>
                    <td>@item.Product.Price</td>
                    <td>@item.Amount</td>
                    <form asp-page-handler="Delete" method="post">
                    <th>
                        <input hidden value="@item.Product.ProductId" asp-for="Product.ProductId">
                        <button class="btn waves-effect waves-light red darken-1" type="submit">
                            <i class="material-icons">delete</i>
                        </button>
                    </th>
                    </form>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <div>Total pris: @Model.TotalPrice kr.</div>
    <br />
    @if (string.IsNullOrEmpty(HttpContext.Session.GetString("userId")))
    {
        <a class="waves-effect waves-light btn view col l2" asp-page="/Users/Login">Login</a>
    }
    else if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Cart")))
    {
        <a class="waves-effect waves-light btn view col l2" onclick="$('#modal1').modal('open');">Bestil</a>
    }
    else
    {
        <a class="waves-effect waves-light btn view col l2" asp-page="/Products/AllProducts">Find Product</a>
    }
    <br />

    @if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userId")))
    {
        <div id="modal1" class="modal">
            <div class="modal-content">
                <div class="row">
                    <h4 class="col">Opret ordre</h4>
                    <a href="#!" class="modal-close waves-effect waves-green btn-flat right col">Luk</a>
                </div>
                <form class="col s12" method="post">
                    <div class="row">
                        <div class="input-field col s6">
                            <select asp-for="Ordre.Fk_DeliveryId" asp-items="@Model.Deliverys" required>
                                <option value="">Valg</option>
                            </select>
                            <label>Levering</label>
                        </div>
                        <div class="input-field col s6">
                            <select asp-for="Ordre.Fk_PayementId" asp-items="@Model.Payments" required>
                                <option value="">Valg</option>
                            </select>
                            <label>Betalings måde</label>
                        </div>
                    </div>
                    <div class="row">
                        <p>Addresse: @Model.User.Address</p>
                        <p>Postnummer: @Model.User.Fk_ZipCodeId @Model.User.ZipCode.City</p>
                    </div>

                    <button class="btn waves-effect waves-light" type="submit" name="action" asp-page-handler="Create">
                        Bestil
                        <i class="material-icons right">send</i>
                    </button>
                </form>
            </div>
        </div>

    }
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#modal1').modal();
    });
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>

WebLayer/Pages/Products/UpdateProduct.cshtml
@page "{ProductId:int}"
@model WebLayer.Pages.Products.UpdateProductModel
@{
    ViewData["Title"] = "Rediger";
}
<br />
<form class="container" method="post" enctype="multipart/form-data">
    <h3>Rediger</h3>
    <br />
    <input hidden asp-for="Product.ProductId" />
    <input hidden asp-for="Product.Image.Path" />
    <div class="row">
        <div class="input-field">
            <input asp-for="Product.Name" id="first_name" type="text" class="validate">
            <label for="first_name">Title</label>
        </div>
    </div>
    <div class="input-field">
        <input asp-for="Product.Description" id="description" type="text" class="validate">
        <label for="description">Beskrivlse</label>
    </div>
    <div class="row">
        <div class="input-field col s6">
            <input id="icon_add" type="text" step="any" asp-for="Product.Price">
            <label for="icon_add">Pris</label>
            <span class="text-darken-1" asp-validation-for="@Model.Product.Price"></span>
        </div>
        <div class="input-field col s6">
            <select asp-for="Product.Fk_SetId" asp-items="@Model.Sets" required>
                <option value="">Valg</option>
            </select>
            <label>Set</label>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s6">
            <select asp-for="Product.Fk_BrandId" asp-items="@Model.Brands" required>
                <option value="">Valg</option>
            </select>
            <label>Brand</label>
        </div>
        <div class="input-field col s6">
            <select asp-for="Product.Fk_CategoryId" asp-items="@Model.Catagories" required>
                <option value="">Valg</option>
            </select>
            <label>Kategori</label>
        </div>
    </div>
    <div class="row">
        <div class="col s6">
            <img class="img-wh" src="@Model.Product.Image.Path" />
        </div>
        <div class="file-field input-field">
            <div class="btn">
                <span>File</span>
                <input type="file" asp-for="UploadImage">
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
            </div>
        </div>
    </div>
    <button class="btn waves-effect waves-light" type="submit" name="action" asp-page-handler="Update">
        Rediger
        <i class="material-icons right">send</i>
    </button>
</form>
<br />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>